#ifndef __MATRIXKEY_H
#define __MATRIXKEY_H

#include "gpio.h"

#define KEY_NO_PREESED 0xFF
/* 矩阵按键值 MATRIX_KEY_NOPRESS表示未按下*/
typedef enum {
	MATRIX_KEY_0 = 0x00,
	MATRIX_KEY_1 = 0x01,
	MATRIX_KEY_2 = 0x02,
	MATRIX_KEY_3 = 0x03,
	MATRIX_KEY_4 = 0x04,
	MATRIX_KEY_5 = 0x05,
	MATRIX_KEY_6 = 0x06,
	MATRIX_KEY_7 = 0x07,
	MATRIX_KEY_8 = 0x08,
	MATRIX_KEY_9 = 0x09,
	MATRIX_KEY_A = 0x0A,
	MATRIX_KEY_B = 0x0B,
	MATRIX_KEY_C = 0x0C,
	MATRIX_KEY_D = 0x0D,
	MATRIX_KEY_MUL	 = 0x0F,	/* 乘号 */
	MATRIX_KEY_POUND = 0x0E,	/* 井号 */
	MATRIX_KEY_NOPRESS = KEY_NO_PREESED,
}MATRIX_KEY_NUM;	

/* PB3、4、8、9 行输出 */
#define KEY_ROW1_OUT_HIGH HAL_GPIO_WritePin(GPIOB, GPIO_PIN_3, GPIO_PIN_SET)
#define KEY_ROW2_OUT_HIGH HAL_GPIO_WritePin(GPIOB, GPIO_PIN_4, GPIO_PIN_SET)
#define KEY_ROW3_OUT_HIGH HAL_GPIO_WritePin(GPIOB, GPIO_PIN_8, GPIO_PIN_SET)
#define KEY_ROW4_OUT_HIGH HAL_GPIO_WritePin(GPIOB, GPIO_PIN_9, GPIO_PIN_SET)
            
#define KEY_ROW1_OUT_LOW HAL_GPIO_WritePin(GPIOB, GPIO_PIN_3, GPIO_PIN_RESET)
#define KEY_ROW2_OUT_LOW HAL_GPIO_WritePin(GPIOB, GPIO_PIN_4, GPIO_PIN_RESET)
#define KEY_ROW3_OUT_LOW HAL_GPIO_WritePin(GPIOB, GPIO_PIN_8, GPIO_PIN_RESET)
#define KEY_ROW4_OUT_LOW HAL_GPIO_WritePin(GPIOB, GPIO_PIN_9, GPIO_PIN_RESET)

/* 第一行输出低电平 其他行高电平*/
#define MATRIXKEY_ROW_HIGH_BUT_1 \
{\
	KEY_ROW1_OUT_LOW;\
	KEY_ROW2_OUT_HIGH;\
	KEY_ROW3_OUT_HIGH;\
	KEY_ROW4_OUT_HIGH;\
}
/* 第二行输出低电平 其他行高电平*/
#define MATRIXKEY_ROW_HIGH_BUT_2 \
{\
	KEY_ROW1_OUT_HIGH;\
	KEY_ROW2_OUT_LOW;\
	KEY_ROW3_OUT_HIGH;\
	KEY_ROW4_OUT_HIGH;\
}
/* 第三行输出低电平 其他行高电平*/
#define MATRIXKEY_ROW_HIGH_BUT_3 \
{\
	KEY_ROW1_OUT_HIGH;\
	KEY_ROW2_OUT_HIGH;\
	KEY_ROW3_OUT_LOW;\
	KEY_ROW4_OUT_HIGH;\
}
/* 第四行输出低电平 其他行高电平*/
#define MATRIXKEY_ROW_HIGH_BUT_4 \
{\
	KEY_ROW1_OUT_HIGH;\
	KEY_ROW2_OUT_HIGH;\
	KEY_ROW3_OUT_HIGH;\
	KEY_ROW4_OUT_LOW;\
}


uint8_t MatrixKey_GetNum(void); /* 获取按键值 */



#endif
